# Generated by Django 6.0.7 on 2026-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacion', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('titular', models.CharField(help_text='Ej: Desarrollador Web Backend', max_length=200)),
                ('bio_corta', models.TextField()),
                ('bio_larga', models.TextField()),
                ('email_contacto', models.EmailField(max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Perfil Global',
                'verbose_name_plural': 'Perfil Global',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('db', 'Bases de Datos'), ('tools', 'Herramientas')], max_length=20)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.TextField()),
                ('imagen_portada', models.ImageField(upload_to='proyectos/portadas/')),
                ('repositorio_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tecnologias', models.ManyToManyField(related_name='proyectos', to='portfolio.tecnologia')),
            ],
            options={
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('tecnologias_usadas', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
            options={
                'ordering': ['-actual', '-fecha_inicio'],
            },
        ),
    ]
